server:
  port: 8084

spring:
  application:
    name: stockcrawling-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: stockcrawling-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "in.stockcrawlingservice.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      properties:
        max.block.ms: 120000 # 2분으로 설정

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://crawlingdb:3306/crawlingdb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  batch:
    jdbc:
      initialize-schema: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}



logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS, Asia/Seoul} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS, Asia/Seoul} %5p ${PID:- } --- [%t] %-40.40logger{39} : %m%n%wEx"


KIS:
  APPKey: PSFKTQQ2RiIZYUfxpVu5uGxs9UoOHPaCX5GG
  APPSecret: QMiQMF6DN28DCCt8er8lddxGx2fpvRyd1e1u5bd/cE/d2I9LV5dbisokDS8MHyIi34ZPFm6Rli/EbHOR+5ckEWN/mco9A7wl8FjKaE4cZI+Ch+lcCmYbmD6ZL98+3Vy6n8swIxkv65UsuXY3kujfyAg6uCY2d2ogTPy/B7E5599uBXnX46k=