apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
      tier: backend
  template:
    metadata:
      labels:
        app: auth-service
        tier: backend
    spec:
      containers:
        - name: auth-service-container
          image: inyoung155/user-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: REDIS_HOST
              value: "host.docker.internal"
            - name: REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3003
  selector:
    app: auth-service
    tier: backend