apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawling-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crawling-service
      tier: backend
  template:
    metadata:
      labels:
        app: crawling-service
        tier: backend
    spec:
      containers:
        - name: crawling-service-container
          image: inyoung155/stockroom-stockcrawling-service
          ports:
            - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: crawling-service-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3002
  selector:
    app: crawling-service
    tier: backend