apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-service
      tier: backend
  template:
    metadata:
      labels:
        app: stock-service
        tier: backend
    spec:
      containers:
        - name: stock-service-container
          image: inyoung155/stockroom-stock-service
          ports:
            - containerPort: 3001
          env:
            - name: REDIS_HOST
              value: "host.docker.internal"  # 로컬에서 도커를 띄움
            - name: REDIS_PORT
              value: "6379" # minikube ssh -- sudo ip route add 172.17.0.0/16 via $(minikube ip)

---
apiVersion: v1
kind: Service
metadata:
  name: stock-service-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: stock-service
    tier: backend