server:
 port: 8080

spring:
 cloud:
  gateway:
   routes:
    - id: user
      uri: http://localhost:8081
      predicates:
      - Path=/api/user/**
    - id: activity
      uri: http://localhost:8082
      predicates:
      - Path=/api/activity/**
    - id: newsFeed
      uri: http://localhost:8083
      predicates:
      - Path=/api/newsFeed/**